version: 2.1

jobs:
  install-deps:
    docker:
      - image: cimg/node:14.17.0
    working_directory: ~/project
    steps:
      - checkout
      - restore_cache:
          keys:
            - node_deps-{{ checksum "yarn.lock" }}
      - run:
          command: yarn --frozen-lockfile
      - save_cache:
          key: node_deps-{{ checksum "yarn.lock" }}
          paths:
            - ~/project/node_modules
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  lint-and-test:
    docker:
      - image: cimg/node:14.17.0
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: check code follow standard
          command: yarn check-all
      - run:
          name: tests
          command: yarn test

  build-windows:
    docker:
      - image: electronuserland/builder:wine
    steps:
      - checkout
      - run: yarn && yarn make
      - store_artifacts:
          path: ~repo/out

  build-macos:
    macos:
      xcode: 11.3.0
    steps:
      - checkout
      - run: security create-keychain -p $KEYCHAIN_PASSWORD build.keychain
      - run: security default-keychain -s build.keychain
      - run: security unlock-keychain -p $KEYCHAIN_PASSWORD build.keychain
      - run: echo $KEYSTORE | base64 --decode - > keystore.p12
      - run: security import keystore.p12 -k build.keychain -P $KEYCHAIN_PASSWORD -T /usr/bin/codesign
      - run: yarn && yarn make
      - store_artifacts:
          path: ~repo/out

  build-ubuntu:
    docker:
      - image: electronuserland/builder:14
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Install dpkg and fakeroot
          command: |
            apt-get update -y
            apt-get install -y dpkg fakeroot
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Generate Builds
          command: yarn make
      - store_artifacts:
          path: ~/repo/out/make

workflows:
  lint-test-package:
    jobs:
      - install-deps
      - lint-and-test:
          requires:
            - install-deps
      - build-ubuntu:
          requires:
            - lint-and-test
